name: dafallah_nyt
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Bloc for state management
  flutter_bloc: ^8.1.1
  # Service locator
  get_it: ^7.2.0
  # Value equality
  equatable: ^2.0.5
  # Functional programming
  dartz: ^0.10.1
  # Remote API
  internet_connection_checker: ^0.0.1+4
  dio: ^4.0.6
  # Local cache
  shared_preferences: ^2.0.15
  get: ^4.6.5
  # image
  cached_network_image: ^3.2.1
  # date time
  intl: ^0.17.0
  #JsonSerializable 
  json_serializable: ^6.4.0
  json_annotation: ^4.7.0
  


dev_dependencies:
  flutter_lints: ^2.0.0
  lint: ^1.8.2
  flutter_test:
    sdk: flutter
  # A mock framework inspired by Mockito for testing
  mockito: ^5.3.1
  # Testing Http requests
  http_mock_adapter: ^0.3.3
  build_runner: ^2.2.1


flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/images/